### ISSUE TITLE
error trying to run samples

### ISSUE THREAD

**Issue by linspinho** [JFXtras/jfxtras-labs-samples#9]
I am getting problem trying to run java -jar F:\jfxtras-labs-samples-8.0-r6-SNAPSHOT-shadow.jar, as you guys stated on http://jfxtras.org.

C:\Users\MJRN>java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

C:\Users\MJRN>java -jar F:\jfxtras-labs-samples-8.0-r6-SNAPSHOT-shadow.jar
Error: Unable to access jarfile F:\jfxtras-labs-samples-8.0-r6-SNAPSHOT-shadow.jar

C:\Users\MJRN>java -jar F:\jfxtras-labs-samples-8.0-r6-SNAPSHOT-all.jar
Initialising FXSampler sample scanner...
        Discovering projects...
                Found project 'JFxtras', with sample base package 'jfxtras.samples'
                Found project 'JFxtrasLabs', with sample base package 'jfxtras.labs.samples'
java.nio.file.AccessDeniedException: Ambiente de impressão
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(Unknown Source)
        at java.nio.file.Files.newDirectoryStream(Unknown Source)
        at java.nio.file.FileTreeWalker.visit(Unknown Source)
        at java.nio.file.FileTreeWalker.next(Unknown Source)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at fxsampler.util.SampleScanner.scanPath(SampleScanner.java:174)
        at fxsampler.util.SampleScanner.loadFromPathScanning(SampleScanner.java:156)
        at fxsampler.util.SampleScanner.discoverSamples(SampleScanner.java:72)
        at fxsampler.FXSampler.start(FXSampler.java:106)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162 auncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)

In Centos 7 I got even worse infinite error loop!
Where am I wrong??? Can somebody guide me to how run this as easy as possible.

**Comment by tbee** [comment]
Hm. Interesting. JFXtras uses the samples framework from ControlsFX, and this is the fxsampler trying to dynamically find samples to show. Apparently it runs into a file permission problem on Centos. I'll ask Jonathan if he has encountered this before.

**Comment by linspinho** [comment]
Hello tbee, thanks for your time! After you said that JFXtras uses the same ControlsFX's framework, I know I have ControlsFX and 2 days ago I had tried it, so I tried again and this gave me same error, but only 1 page of errors, than I tried JFXtras again and it starts after tons of errors, I mean more than 30 pages, more or less, when I saw the errors I pressed ctrl+c to stop, that is why never works. The errors are like this:

ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNChangelistHandler.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNEvent
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNEvent.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNConflictReason
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNConflictReason.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNInfo
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNInfo.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNUpdateClient
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNUpdateClient.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNCopySource
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNCopySource.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNPropertyConflictDescription
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNPropertyConflictDescription.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNPropertyData
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNPropertyData.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNPropertyHandler
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNPropertyHandler.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNExternalsHandler
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNExternalsHandler.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNAnnotateHandler
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNAnnotateHandler.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNStatusFileProvider
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNStatusFileProvider.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNClientManager
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNClientManager.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNMergeFileSet
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNMergeFileSet.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNDiffStatusHandler
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNDiffStatusHandler.class
ERROR: Class name: org.tmatesoft.svn.core.wc.DefaultSVNDiffGenerator
ERROR: Initial filename: org/tmatesoft/svn/core/wc/DefaultSVNDiffGenerator.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNEventAction
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNEventAction.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNEventAdapter
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNEventAdapter.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNDiffClient
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNDiffClient.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNFileFilter
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNFileFilter.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNRevisionRange
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNRevisionRange.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNConflictResult
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNConflictResult.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNCommitParameters
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNCommitParameters.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNCommitHandler
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNCommitHandler.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNLogClient
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNLogClient.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNAddParameters
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNAddParameters.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNMergerFactory
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNMergerFactory.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNConflictHandler
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNConflictHandler.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNStatusHandler
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNStatusHandler.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNCopyClient
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNCopyClient.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNChangelistClient
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNChangelistClient.class
ERROR: Class name: org.tmatesoft.svn.core.wc.DefaultSVNRepositoryPool
ERROR: Initial filename: org/tmatesoft/svn/core/wc/DefaultSVNRepositoryPool.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNWCUtil
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNWCUtil.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNOperation
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNOperation.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNCommitPacket
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNCommitPacket.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNDiffOptions
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNDiffOptions.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNStatusClient
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNStatusClient.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNStatus
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNStatus.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNWCClient
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNWCClient.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNConflictDescription
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNConflictDescription.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNConflictAction
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNConflictAction.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNCommitItem
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNCommitItem.class
ERROR: Class name: org.tmatesoft.svn.core.wc.DefaultSVNCommitHandler
ERROR: Initial filename: org/tmatesoft/svn/core/wc/DefaultSVNCommitHandler.class
ERROR: Class name: org.tmatesoft.svn.core.wc.ISVNMerger
ERROR: Initial filename: org/tmatesoft/svn/core/wc/ISVNMerger.class
ERROR: Class name: org.tmatesoft.svn.core.wc.SVNMoveClient
ERROR: Initial filename: org/tmatesoft/svn/core/wc/SVNMoveClient.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.patch.SVNPatchHunk
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/patch/SVNPatchHunk.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.patch.SVNPatch
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/patch/SVNPatch.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.patch.SVNPatchTarget
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/patch/SVNPatchTarget.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.patch.SVNPatchTargetInfo
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/patch/SVNPatchTargetInfo.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.patch.SVNPatchHunkInfo
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/patch/SVNPatchHunkInfo.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.patch.SVNPatchFileStream
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/patch/SVNPatchFileStream.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNLog
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/SVNLog.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNAdminArea14Factory
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/SVNAdminArea14Factory.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNChecksumInputStream
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/SVNChecksumInputStream.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNAdminArea15Factory
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/SVNAdminArea15Factory.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNAdminAreaInfo
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/SVNAdminAreaInfo.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNAdminArea16
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/SVNAdminArea16.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNTranslatorOutputStream
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/SVNTranslatorOutputStream.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNProperties13
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/SVNProperties13.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.ISVNEntryHandler
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/ISVNEntryHandler.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNEntry16
ERROR: Initial filename: org/tmatesoft/svn/core/internal/wc/admin/SVNEntry16.class
ERROR: Class name: org.tmatesoft.svn.core.internal.wc.admin.SVNXMLAdminArea

MUCH MORE LIKE THOSES!!!
If you request a can put the rest here.
JFXtras Samples seems working well.
Thanks a lot!
By the way that was in centos 7.

**Comment by tbee** [comment]
I can see what happens if I upgrade FXSampler, but it really is not JFXtras causing them, because those classes are about SVN...?

**Comment by linspinho** [comment]
It is not only SVN only, it is:
ERROR: Class name: org.tigris.subversion.javahl.ChangelistCallback
ERROR: Initial filename: org/tigris/subversion/javahl/ChangelistCallback.class

ERROR: Class name: org.apache.subversion.javahl.callback.StatusCallback
ERROR: Initial filename: org/apache/subversion/javahl/callback/StatusCallback.class

ERROR: Class name: org.eclipse.equinox.internal.simpleconfigurator.manipulator.SimpleConfiguratorManipulatorFactoryImpl
ERROR: Initial filename: org/eclipse/equinox/internal/simpleconfigurator/manipulator/SimpleConfiguratorManipulatorFactoryImpl.class

ERROR: Class name: org.eclipse.jdt.internal.launching.VMListener
ERROR: Initial filename: org/eclipse/jdt/internal/launching/VMListener.class

ERROR: Class name: org.jfree.data.general.DefaultValueDataset
ERROR: Initial filename: org/jfree/data/general/DefaultValueDataset.class

ERROR: Class name: org.eclipse.emf.ecore.xml.type.util.XMLTypeResourceImpl
ERROR: Initial filename: org/eclipse/emf/ecore/xml/type/util/XMLTypeResourceImpl.class

ERROR: Class name: org.apache.batik.css.engine.SVGCSSEngine
ERROR: Initial filename: org/apache/batik/css/engine/SVGCSSEngine.class

ERROR: Class name: org.eclipse.core.internal.net.WindowsProxyProvider
ERROR: Initial filename: org/eclipse/core/internal/net/WindowsProxyProvider.class

ERROR: Class name: org.eclipse.ecf.internal.provider.filetransfer.httpclient4.CloseMonitoringSocket
ERROR: Initial filename: org/eclipse/ecf/internal/provider/filetransfer/httpclient4/CloseMonitoringSocket.class

AND MORE!

I think it is the framework you guys uses to build the samples, cos' ControlsFX shows some identical errosrs, but not that much!

The JFXtras samples works!

**Comment by tbee** [comment]
As said: it seems FXSample is scanning the whole classpath for samples; eclipse, jfree, batik, and running into errors doing so.

**Comment by tbee** [comment]
Jonathan asks if you would want to file this issue on ControlsFX, so they can track the resolution.
https://bitbucket.org/controlsfx/controlsfx

**Comment by Ygarr** [comment]
Still while running samples:
```
 java --module-path C:\ ..\javafx-sdk-18.0.2\lib --add-modules javafx.controls,javafx.fxml,javafx.web -jar .\jfxtras-labs-samples-8.0-r6-SNAPSHOT-all.jar
Initialising FXSampler sample scanner...
        Discovering projects...
                Found project 'JFxtras', with sample base package 'jfxtras.samples'
                Found project 'JFxtrasLabs', with sample base package 'jfxtras.labs.samples'
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1081)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: javafx/scene/paint/LinearGradientBuilder
        at jfxtras.labs.samples.radialmenu.RadialMenuSample.createRadialMenu(RadialMenuSample.java:129)
        at jfxtras.labs.samples.radialmenu.RadialMenuSample.<init>(RadialMenuSample.java:53)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341)
        at java.base/java.lang.Class.newInstance(Class.java:677)
        at fxsampler.util.SampleScanner.discoverSamples(SampleScanner.java:86)
        at fxsampler.FXSampler.start(FXSampler.java:106)
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
        at javafx.graphics@18.0.2/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at javafx.graphics@18.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.graphics@18.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at javafx.graphics@18.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics@18.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics@18.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: javafx.scene.paint.LinearGradientBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 18 more
Exception running application fxsampler.FXSampler
```
